### ISSUE TITLE
Health-bar is red at the beginning - reverts with first hit.

### ISSUE THREAD

**Issue by ghost** [BitfoxCanada/bruh-io-bug-tracker#11] opened 2018-01-12 20:23 UTC
<img width="749" alt="screen shot 2018-01-12 at 21 22 29" src="https://user-images.githubusercontent.com/35238821/34893729-dc7660e6-f7de-11e7-8328-b5f89d72c2ba.png">

**Comment by asdad-github** [comment] 2018-01-12 20:30
Happens every other game now.

**Comment by asdad-github** [comment] 2018-01-12 20:31
And this after the start:
<img width="881" alt="a" src="https://user-images.githubusercontent.com/35238821/34893997-e40b257a-f7df-11e7-89f2-feff0f0519d9.png">
<img width="813" alt="b" src="https://user-images.githubusercontent.com/35238821/34894001-e6d68af6-f7df-11e7-8e27-596665e6dd80.png">

**Comment by Samstiles** [comment] 2018-02-23 16:19
Thanks for the bug report! This is a duplicate of #2 (they're all the same bug in the engine, a part of the engine called the interpolator), so I'm going to close this issue. Feel free to follow progress on bug #2 if you're curious.

**Closed by Samstiles** 2018-02-23 16:19 UTC

**Comment by Samstiles** [comment] 2018-03-05 02:36
This is fixed now!
