### ISSUE TITLE
Speeding alive players still a thing :/ (France A1, atm)

### ISSUE THREAD

**Issue by ghost** [BitfoxCanada/bruh-io-bug-tracker#6] opened 2018-01-09 14:06 UTC

**Comment by Samstiles** [comment] 2018-02-23 16:16
Thanks for the bug report! This is a duplicate of bug #2 so I'm going to close it for now :)

**Closed by Samstiles** 2018-02-23 16:16 UTC

**Comment by Samstiles** [comment] 2018-03-05 02:35
This is fixed now!
