### ISSUE TITLE
Machine Gun Firing with default Pistol

### ISSUE THREAD

**Issue by Straflight** [BitfoxCanada/bruh-io-bug-tracker#13] opened 2018-01-26 15:34 UTC
![screenshot 2018-01-26 at 9 40 24 am](https://user-images.githubusercontent.com/35843778/35447322-04856c32-027d-11e8-84a6-c9bf91c3faf8.png)
There is a weird glitch where my fire rate is extremely high, even though I just have a pistol. My ammo is also 100 like a machine gun would have. Can you guys fix this bug, please?

**Comment by Samstiles** [comment] 2018-02-23 16:20
Thanks for the bug report! This is a duplicate of #2 (they're all the same bug in the engine, a part of the engine called the interpolator), so I'm going to close this issue. Feel free to follow progress on bug #2 if you're curious.

**Closed by Samstiles** 2018-02-23 16:20 UTC

**Comment by Samstiles** [comment] 2018-03-05 02:36
This is fixed now!
