### ISSUE TITLE
ghost bug

### ISSUE THREAD

**Issue by Gnar432626** [BitfoxCanada/bruh-io-bug-tracker#5] opened 2018-01-09 12:09 UTC
i just had that bug
and 
![capture](https://user-images.githubusercontent.com/35105666/34720241-fb1bb8a0-f50b-11e7-9c95-60d719ccfd32.PNG)

  i was alive and working and i don't think people saw me as that because when i went up to them they just did nothing

**Comment by Samstiles** [comment] 2018-02-23 16:16
Thanks for the bug report! This is a duplicate of bug #2 so I'm going to close it for now :)

**Closed by Samstiles** 2018-02-23 16:16 UTC
